name: Data Preprocessing Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn
        
    - name: Run preprocessing
      run: |
        cd preprocessing
        python automate_Sava_Reyhano.py --input "../Heart Attack.csv" --output "../dataset_preprocessing/processed_data.csv"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dataset_preprocessing/processed_data.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update processed dataset" && git push)
